### ISSUE TITLE
NaiveBayes.Gaussian.fit internal tensor shape error

### ISSUE THREAD

**Issue by rktjmp** [elixir-nx/scholar#152]
When I run `Scholar.NaiveBayes.Gaussian.fit`, I get an error about a tensor shape mismatch between the while's initial value and internal return value.

The 7th and 8th tensors in the error message are being recast from float64 to float32 (2nd and 3rd from the end) during the while iteration. (My tensors are f64 instead of f32 because they are coming from an Explorer data frame, which is why the reproduction casts types them as f64.) 

Casting my tensor down before fitting works but is probably not ideal in all cases.

```elixir
# version elixir-1.14.2
# cuda 118
Mix.install(
  [
    {:nx, "~> 0.5.0"},
    {:explorer, "~> 0.6.0"},
    {:scholar, "~> 0.1.0"},
    {:axon, "~> 0.5.0"},
    {:vega_lite, "~> 0.1.7"},
    {:kino, "~> 0.10.0"},
    {:kino_explorer, "~> 0.1.4"},
    {:kino_vega_lite, "~> 0.1.8"},
    {:exla, "~> 0.5.0"}
  ],
  config: [
    nx: [default_backend: EXLA.Backend]
  ]
)

Nx.Defn.default_options(compiler: EXLA)
```
```elixir
x =
  [
    [
      -0.15822920539850216,
      -0.11012251222980245,
      -0.12866923530818172,
      -0.6708581633526598,
      -0.6495316298866598,
      0.4759795967356525,
      0.8315648333009558,
      -0.8462183658799857,
      -0.5646687045582609,
      -1.4643804864551344
    ]
  ]
  |> Nx.tensor(type: :f64)

y =
  [1]
  |> Nx.tensor(type: :u8)

Scholar.NaiveBayes.Gaussian.fit(x, y, num_classes: 2)
```

```

** (CompileError) .cache/mix/installs/elixir-1.14.2-erts-13.1.2/f04257a1f822a4a6e758aa52a9cd01a0/deps/scholar/lib/scholar/naive_bayes/gaussian.ex:298: the do-block in while must return tensors with the same shape, type, and names as the initial arguments.

Body matches template:

{#Nx.Tensor<
   s64
 >, #Nx.Tensor<
   f64[4][10]
 >, #Nx.Tensor<
   s64[4]
 >, #Nx.Tensor<
   f32[4]
 >, #Nx.Tensor<
   s64[2]
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   f64[2][10]
 >, #Nx.Tensor<
   f64[2][10]
 >, #Nx.Tensor<
   f32[2]
 >}

and initial argument has template:

{#Nx.Tensor<
   s64
 >, #Nx.Tensor<
   f64[4][10]
 >, #Nx.Tensor<
   s64[4]
 >, #Nx.Tensor<
   f32[4]
 >, #Nx.Tensor<
   s64[2]
 >, #Nx.Tensor<
   u8
 >, #Nx.Tensor<
   f32[2][10]
 >, #Nx.Tensor<
   f32[2][10]
 >, #Nx.Tensor<
   f32[2]
 >}

    (nx 0.5.3) lib/nx/defn/expr.ex:483: Nx.Defn.Expr.compatible_while!/4
    (nx 0.5.3) lib/nx/defn/expr.ex:354: Nx.Defn.Expr.defn_while/6
    (scholar 0.1.0) lib/scholar/naive_bayes/gaussian.ex:298: Scholar.NaiveBayes.Gaussian."__defn:fit_n__"/6
    (nx 0.5.3) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.5.3) lib/exla/defn.ex:385: anonymous fn/4 in EXLA.Defn.compile/8
    (exla 0.5.3) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.1.1) timer.erl:235: :timer.tc/1
    #cell:roe7i2jbufgvae6sehp4wuw6ri5rly4e:58: (file)
```

**Comment by msluszniak** [comment]
The problem is not in shape but in type. Look that the 7th and 8th tensors in the first one are type `:f64` and in the second one are `:f32`. I will fix this now since it's a trivial fix

**Comment by msluszniak** [comment]
@rktjmp, I tried to recreate the bug on the scholar from the `main` branch and I got the correct result:

```
%Scholar.NaiveBayes.Gaussian{
  theta: #Nx.Tensor<
    f64[2][10]
    [
      [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN],
      [-0.15822920539850216, -0.11012251222980245, -0.12866923530818172, -0.6708581633526598, -0.6495316298866598, 0.4759795967356525, 0.8315648333009558, -0.8462183658799857, -0.5646687045582609, -1.4643804864551344]
    ]
  >,
  var: #Nx.Tensor<
    f64[2][10]
    [
      [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN],
      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    ]
  >,
  class_count: #Nx.Tensor<
    f64[2]
    [0.0, 1.0]
  >,
  class_priors: #Nx.Tensor<
    f64[2]
    [0.0, 1.0]
  >,
  classes: #Nx.Tensor<
    s64[2]
    [0, 1]
  >,
  epsilon: #Nx.Tensor<
    f64
    0.0
  >
}
```

I think that this problem has been solved already in `main`, but would be grateful if you confirm. As the `Nx` 0.6 will be released, we immediately release `Scholar` 0.2 ;)

**Comment by rktjmp** [comment]
I'm getting polaris build errors when I try to build against main. Happy to take your word that it's fixed though.

```
Mix.install([
  {:nx, git: "https://github.com/elixir-nx/nx/", override: true},
  {:scholar, git: "https://github.com/elixir-nx/scholar/", override: true},
  {:polaris, git: "https://github.com/elixir-nx/polaris/", override: true}
  # {:exla, "~> 0.5.0"}
])
```

```
==> polaris
Compiling 5 files (.ex)

== Compilation error in file lib/polaris/schedules.ex ==
** (CompileError) lib/polaris/schedules.ex:24: module Nx.Defn is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
```

**Comment by msluszniak** [comment]
@polvalente maybe you'll be able to help with Polaris

**Comment by msluszniak** [comment]
> Mix.install([
  {:nx, git: "https://github.com/elixir-nx/nx/", override: true},
  {:scholar, git: "https://github.com/elixir-nx/scholar/", override: true},
  {:polaris, git: "https://github.com/elixir-nx/polaris/", override: true}
])

Maybe try installing only `Scholar` without `Nx` and `Polaris`.

**Comment by rktjmp** [comment]
Yep that worked and I can confirm the error is fixed.

**Comment by polvalente** [comment]
The problem is that to install Nx from git you need to specify the `:sparse` option as well:

`{:nx, github: "elixir-nx/nx", sparse: "nx", override: true}`

This is needed because the elixir-nx/nx repo contains 3 libs and none of those are in the root directory.
