### ISSUE TITLE
KMeans fit function error

### ISSUE THREAD

**Issue by santiago-imelio** [elixir-nx/scholar#221]
Hello, I was updating the libraries on my california housing livebook with the latest changes and I encountered an error after trying to fit KMeans. I was able to reproduce the bug on a [separate notebook](https://github.com/santiago-imelio/my_livebooks/commit/f463b15e169526e99039d70ab230b8c517afdc7a?short_path=b970ba6#diff-b970ba6764cb82c596a33742f9306813bcb2556b157297d1b2368b6cf41ad0a1).
Works fine using older versions
```elixir
  {:nx, "~> 0.2"},
  {:exla, "~> 0.5"},
  {:scholar, "~> 0.1"},
```
Here's the error
```
** (MatchError) no match of right hand side value: [#Nx.Tensor<
    f64[10][20640]
    
    Nx.Defn.Expr
    parameter a:2                                                   f64[20640][2]
    parameter e:0                                                   f64[10][10][2]
    b = reshape a                                                   f64[1][1][1][20640][1][2]
    c = broadcast b, {10, 1, 10, 20640, 1, 2}, [0, 1, 2, 3, 4, 5]   f64[10][1][10][20640][1][2]
    d = reshape c                                                   f64[10][206400][2]
    f = reshape e                                                   f64[10][10][1][2]
    g = broadcast f, {10, 10, 20640, 2}, [0, 1, 2, 3]               f64[10][10][20640][2]
    h = reshape g                                                   f64[10][206400][2]
    i = subtract d, h                                               f64[10][206400][2]
    j = multiply i, i                                               f64[10][206400][2]
    k = sum j, axes: [2], keep_axes: false                          f64[10][206400]
    l = reshape k                                                   f64[10][10][20640]
    m = reduce_min l, axes: [1], keep_axes: false                   f64[10][20640]
    n = cumulative_sum m, axis: 1, reverse: false                   f64[10][20640]
  >, #Nx.Tensor<
    f64[10][20640]
    
    Nx.Defn.Expr
    parameter a:0                                f64[10][20640]
    ...                                          
    b = slice a, [0, 0], [10, 20639], [1, 2]     f64[10][10320]
    c = slice b, [0, 0], [10, 1], [1, 1]         f64[10][1]
    d = slice a, [0, 1], [10, 20639], [1, 2]     f64[10][10320]
    e = add d, b                                 f64[10][10320]
    f = slice e, [0, 0], [10, 10319], [1, 2]     f64[10][5160]
    g = slice f, [0, 0], [10, 1], [1, 1]         f64[10][1]
    h = slice e, [0, 1], [10, 10319], [1, 2]     f64[10][5160]
    i = add h, f                                 f64[10][5160]
    j = slice i, [0, 0], [10, 5159], [1, 2]      f64[10][2580]
    k = slice j, [0, 0], [10, 1], [1, 1]         f64[10][1]
    l = slice i, [0, 1], [10, 5159], [1, 2]      f64[10][2580]
    m = add l, j                                 f64[10][2580]
    n = slice m, [0, 0], [10, 2579], [1, 2]      f64[10][1290]
    o = slice n, [0, 0], [10, 1], [1, 1]         f64[10][1]
    p = slice m, [0, 1], [10, 2579], [1, 2]      f64[10][1290]
    q = add p, n                                 f64[10][1290]
    r = slice q, [0, 0], [10, 1289], [1, 2]      f64[10][645]
    s = slice r, [0, 0], [10, 1], [1, 1]         f64[10][1]
    v = add t, u                                 f64[10][644]
    w = concatenate [s, v], 1                    f64[10][645]
    x = reshape w                                f64[10][645][1]
    z = concatenate [x, y], 2                    f64[10][645][2]
    ba = reshape z                               f64[10][1290]
    bb = slice ba, [0, 0], [10, 1289], [1, 1]    f64[10][1289]
    bd = add bb, bc                              f64[10][1289]
    be = concatenate [o, bd], 1                  f64[10][1290]
    bf = reshape be                              f64[10][1290][1]
    bh = concatenate [bf, bg], 2                 f64[10][1290][2]
    bi = reshape bh                              f64[10][2580]
    bj = slice bi, [0, 0], [10, 2579], [1, 1]    f64[10][2579]
    bl = add bj, bk                              f64[10][2579]
    bm = concatenate [k, bl], 1                  f64[10][2580]
    bn = reshape bm                              f64[10][2580][1]
    bp = concatenate [bn, bo], 2                 f64[10][2580][2]
    bq = reshape bp                              f64[10][5160]
    br = slice bq, [0, 0], [10, 5159], [1, 1]    f64[10][5159]
    bt = add br, bs                              f64[10][5159]
    bu = concatenate [g, bt], 1                  f64[10][5160]
    bv = reshape bu                              f64[10][5160][1]
    bx = concatenate [bv, bw], 2                 f64[10][5160][2]
    by = reshape bx                              f64[10][10320]
    bz = slice by, [0, 0], [10, 10319], [1, 1]   f64[10][10319]
    cb = add bz, ca                              f64[10][10319]
    cc = concatenate [c, cb], 1                  f64[10][10320]
    cd = reshape cc                              f64[10][10320][1]
    cf = concatenate [cd, ce], 2                 f64[10][10320][2]
    cg = reshape cf                              f64[10][20640]
  >, #Function<149.82431601/2 in Nx.cumulative_op/4>]
    (exla 0.6.4) lib/exla/defn.ex:547: EXLA.Defn.cached_recur_operator/4
    (exla 0.6.4) lib/exla/defn.ex:486: EXLA.Defn.recur_operator/3
    (elixir 1.15.7) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.15.7) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (exla 0.6.4) lib/exla/defn.ex:593: EXLA.Defn.cached_recur_operator/4
    (exla 0.6.4) lib/exla/defn.ex:486: EXLA.Defn.recur_operator/3
    (elixir 1.15.7) lib/enum.ex:1819: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    #cell:u5gwvqu6m2ewvlcstxbam2ejectp24pd:6: (file)
```

**Comment by josevalim** [comment]
You also need to use EXLA from git, if you are using Nx from git.

    {:exla, github: "elixir-nx/nx", sparse: "exla", override: true},
